import CATEGORY_QUERY from './Category';
import CATEGORIES_QUERY from './Categories';
// import CREATE_CATEGORY_MUTATION from './CreateCATEGORY';
// import UPDATE_CATEGORY_MUTATION from './UpdateCATEGORY';
// import DELETE_CATEGORY_MUTATION from './DeleteCATEGORY';

export { 
  CATEGORY_QUERY, 
  CATEGORIES_QUERY, 
  // CREATE_CATEGORY_MUTATION,
  // UPDATE_CATEGORY_MUTATION,
  // DELETE_CATEGORY_MUTATION
}